OnInit(function()

    local main = BlzCreateFrame("EscMenuBackdrop", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0)
    BlzFrameSetAbsPoint(main, FRAMEPOINT_CENTER, 0.4, 0.35)
    BlzFrameSetSize(main, 0.3, 0.35)
    BlzFrameSetVisible(main, GetLocalPlayer() == Player(0))

    local buttonCurved = BlzCreateFrameByType("GLUETEXTBUTTON", "MyScriptDialogButton", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "ScriptDialogButton", 0)
    BlzFrameSetPoint(buttonCurved, FRAMEPOINT_CENTER, main, FRAMEPOINT_CENTER, 0, -0.02)
    BlzFrameSetText(buttonCurved, "CURVED")
    BlzFrameSetVisible(buttonCurved, GetLocalPlayer() == Player(0))

    local buttonUnion = BlzCreateFrameByType("GLUETEXTBUTTON", "MyScriptDialogButton", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "ScriptDialogButton", 0)
    BlzFrameSetPoint(buttonUnion, FRAMEPOINT_CENTER, main, FRAMEPOINT_CENTER, 0, 0.02)
    BlzFrameSetText(buttonUnion, "UNITED")
    BlzFrameSetVisible(buttonUnion, GetLocalPlayer() == Player(0))

    local trig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(trig, buttonCurved, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(trig, function()
        BlzFrameSetVisible(main, FALSE)
        BlzFrameSetVisible(buttonCurved, FALSE)
        BlzFrameSetVisible(buttonUnion, FALSE)
        print("7")
        initMain('curved')
        initialUI()
        initTimers()
        initTriggers()
        --changeAvailableUnitsForPlayers(all_players, all_units, TRUE)
    end)

    local trig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(trig, buttonUnion, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(trig, function()
        BlzFrameSetVisible(main, FALSE)
        BlzFrameSetVisible(buttonCurved, FALSE)
        BlzFrameSetVisible(buttonUnion, FALSE)
        print("7")
        initMain('united')
        initialUI()
        initTimers()
        initTriggers()
        --changeAvailableUnitsForPlayers(all_players, all_units, TRUE)
    end)

end)
