function initTriggers()
    incomeTrigger()
    moveByPointsTrigger()
    loseTrigger()
    winTrigger()
    goldExtractorTrigger()
    finishResearchTrigger()
    enableUpdateTrigger()
    customCastAITrigger()
    spellFinishTrigger()
    spawnTrigger()
    initHeroTriggers()
    cellTrigger()
    moveTrigger()
    summonTrigger()
    debugTrigger()
    debugTriggerGold()
end