function initTriggers()
    incomeTrigger()
    moveByPointsTrigger()
    winLoseTrigger()
    goldExtractorTrigger()
    finishResearchTrigger()
    enableUpdateTrigger()
    customCastAITrigger()
    spellFinishTrigger()
    spawnTrigger()
    heroResearchTrigger()
    heroConstructTrigger()
    heroDeadTrigger()
    debugTrigger()
end