Debug.beginFile('hero-main.lua')
function initHeroTriggers()
    heroResearchTrigger()
    heroConstructTrigger()
    heroDeadTrigger()
    heroTransferExp()
    heroLearnAbility()
    heroNewSkill()
    wardenTrigger()
end
Debug.endFile()